let stopwords = ["about","above","abroad","according","accordingly","across","actually","adj","after","afterwards",
  "against","ago","ahead","ain't","all","allow","allows","almost","along","alongside","already","also","although","always",
  "am","amid","amidst","among","amongst","an","and","another","any","anybody","anyhow","anyone","anything","anyway","anyways","appropriate","are","aren't","around","as","a's","aside",
  "at","away","awfully","back","backward","backwards","be","became","because","become","becomes","becoming","been",
  "before","below","beside","besides","best","better","between","beyond","both",
  "but","by","came","can","cannot","cant","can't","cause","causes","certainly","changes","clearly",
  "c'mon","co","co.","com","contain","containing",
  "corresponding","could","couldn't","course","c's","currently","daren't","definitely","described","despite","did","didn't",
  "different","directly","do","does","doesn't","doing","done","don't","down","downwards","during","each","edu","eg",
  "either","else","elsewhere","ending","entirely","especially","et","etc","even","ever","evermore","every",
  "ex","exactly","example","except","fairly","farther","for","former","formerly","forth","from","further","furthermore",
  "get","gets","getting","given","gives","go","goes","going","got","gotten","had","hadn't","half","happens",
  "hardly","has","hasn't","have","haven't","having","he","he'd","he'll","help","hence","her","here","hereafter","hereby",
  "herein","here's","hereupon","hers","herself","he's","hi","him","himself","his","hither","hopefully","how","howbeit","however",
  "i'd","ie","if","i'll","i'm","immediate","in","inasmuch","inc","inc.",
  "indicates","inner","inside","insofar","instead","into","inward","is","isn't","it","it'd","it'll","its","it's","itself","i've",
  "just","k","keep","keeps","kept","know","known","knows","last","lately","later","latter","latterly","least","less","lest","let",
  "let's","like","liked","likely","likewise","look","looking","looks","low","lower","ltd","made","mainly","make","makes",
  "many","may","maybe","mayn't","me","meantime","meanwhile","merely","might","mightn't","mine","moreover",
  "most","mostly","mr","mrs","much","must","mustn't","my","myself","nd","near","nearly","needn't",
  "needs","neither","never","neverf","neverless","nevertheless","new","next","no","non","none","nonetheless",
  "noone","no-one","nor","normally","not","notwithstanding","of","off","often","oh","ok","ohh",
  "okay","old","on","once","one","ones","one's","only","onto","or","other","others","otherwise","ought","oughtn't","our",
  "ours","ourselves","out","outside","over","overall","own","particular","particularly","past","per","perhaps","placed","please",
  "plus","possible","presumably","probably","provided","provides","que","quite","qv","rather","rd","re","really","reasonably","recent",
  "recently","regarding","regardless","regards","relatively","respectively","right","round","said","same","saw","say","saying",
  "says","secondly","see","seeing","seem","seemed","seeming","seems","seen","self","selves","sensible","sent","serious",
  "shall","shan't","she","she'd","she'll","she's","should","shouldn't","since","so","some",
  "somebody","someday","somehow","someone","something","sometime","sometimes","somewhat","somewhere","soon","sorry","specified",
  "specify","specifying","still","sub","such","sup","sure","take","taken","taking","tends","th","than",
  "thanx","that","that'll","thats","that's","that've","the","their","theirs","them","themselves","then","thence","there","thereafter",
  "thereby","there'd","therefore","therein","there'll","there're","theres","there's","thereupon","there've","these","they","they'd",
  "they'll","they're","they've","thing","things","think","third","thirty","this","thorough","thoroughly","those","though","three",
  "through","throughout","thru","thus","till","to","together","too","took","toward","towards",
  "t's","two","un","under","underneath","undoing","unfortunately","unless","unlike","unlikely","until","unto","up","upon",
  "upwards","us","use","used","useful","uses","using","usually","v","value","various","very","via","viz","vs","want","wants",
  "was","wasn't","way","we","we'd","welcome","well","we'll","went","were","we're","weren't","we've","what","whatever","what'll",
  "what's","what've","when","whence","whenever","where","whereafter","whereas","whereby","wherein","where's","whereupon",
  "whether","which","whichever","while","whilst","whither","who","who'd","whoever","who'll","whom","whomever","who's",
  "whose","why","will","with","within","without","wonder","won't","would","wouldn't","yes","yet","you","you'd","ohh",
  "you'll","your","you're","yours","yourself","yourselves","you've","a","how's","i","when's","why's","b","c","d","e","f",
  "g","h","j","l","m","n","o","p","q","r","s","t","u","uucp","w","x","y","z","I","www","i'll","i'm","ain't","l'm","je","eu",
  "con","couldnt","de","ti","ho","en","ha","vho","mu","te","ka","es","σ'","ft","yo","leo","ci","ap'","tú","wa","don’t","dat",
  "full","give","hasnt","herse","himse","itse”","myse”","part","put","side","vhu","mo","omo","-","i’m","–","em","you’re","eh",
  "top","abst","accordance","affecting","ke","kha","su","se","lei","tha","che","io","hu","ma","il","una","ain’t","i’ll","é",
  "affects","ah","announce","anymore","apparently","approximately","aren","arent","arise","auth","beginning","beginnings","è","di",
  "begins","biol","briefly","ca","date","ed","effect","et-al","ff","fix","gave","giving","heres","hes","hid","home","id","im","da",
  "immediately","importance","important","index","information","invention","itd","keys","kg","km","largely","lets","line","le","lo",
  "'ll","means","mg","ml","mug","na","nay","necessarily","nos","noted","obtain","obtained","omitted","ord","owing","si", "mi","la", 
  "poorly","possibly","potentially","pp","predominantly","present","previously","primarily","promptly","wanna","gonna","tshikwama",
  "quickly","readily","ref","refs","related","research","resulted","resulting","results","run","sec","section","shed","vhaḓe","limpopo",
  "shes","showed","shown","showns","shows","significant","significantly","similar","similarly","slightly","somethan","na","norah",
  "specifically","strongly","substantially","successfully","sufficiently","thered","ya","vashti","radiohead","outkast","var","nah","no","nope",
  "thereof","therere","thereto","theyd","theyre","thou","thoughh","throug","til","tip","ts","ups","usefully","hey","bunyan","yea","yes",
  "usefulness","'ve","vol","vols","wed","whats","wheres","whim","whod","whos","widely","words","youd","youre", "", ">", "-","›","yeah",
  "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "lyrics", "lyric","album","song",
  "ένα","έναν","ένας","αι","ακομα","ακομη","ακριβως","αλλα","αλλαχου","αλλες","αλλη"," αλλην","αλλης","αλλιως","αλλιωτικα","αλλο","αλλοι","αλλοιως","αλλοιωτικα","αλλον","αλλος","αλλοτε","αλλου"," αλλους","αλλων","αμα","αμεσα","αμεσως","αν","ανα","αναμεσα","αναμεταξυ","ανευ","αντι"," αντιπερα","αντις","ανω","ανωτερω","αξαφνα","απ","απο","αποψε","από","αρα","αραγε","αργα"," αργοτερο","αρκετα","αρχικα","ας","αυτα","αυτες","αυτεσ","αυτη","αυτην", "αυτης","αυτο","αυτοι","αυτον","αυτος","αυτοσ","αυτου","αυτους","αυτουσ","αυτων"," αφοτου","αφου","αἱ","αἳ","αἵ","αὐτόσ","αὐτὸς","αὖ","α∆ιακοπα","βεβαια","βεβαιοτατα","γάρ","γα","γα^","γε","γι"," για","γοῦν","","γυρω","γὰρ","δ'","δέ","δή","δαί","δαίσ","δαὶ","δαὶς","δε","δεν","δι","δι'","διά","δια","διὰ"," δὲ","δὴ","δ’","εαν","εαυτο","εαυτον","εαυτου","εαυτους","εαυτων","εγκαιρα","εγκαιρως"," εγω","ειθε","ειμαι","ειμαστε","ειναι","εις","εισαι","εισαστε","ειστε","ειτε","ειχα","ειχαμε","ειχαν","ειχατε"," ειχε","ειχες","ει∆εμη","εκ","εκαστα","εκαστες","εκαστη","εκαστην","εκαστης","εκαστο"," εκαστοι","εκαστον","εκαστος","εκαστου","εκαστους","εκαστων","εκει","εκεινα","εκεινες"," εκεινεσ","εκεινη","εκεινην","εκεινης","εκεινο","εκεινοι","εκεινον","εκεινος","εκεινοσ"," εκεινου","εκεινους","εκεινουσ","εκεινων","εκτος","εμας","εμεις","εμενα","εμπρος","εν"," ενα","εναν","ενας","ενος","εντελως","εντος","εντωμεταξυ","ενω","ενός","εξ","εξαφνα"," εξης","εξισου","εξω","επ","επί","επανω","επειτα","επει∆η","επι","επισης","επομενως"," εσας","εσεις","εσενα","εστω","εσυ","ετερα","ετεραι","ετερας","ετερες","ετερη","ετερης"," ετερο","ετεροι","ετερον","ετερος","ετερου","ετερους","ετερων","ετουτα","ετουτες","ετουτη","ετουτην","ετουτης"," ετουτο","ετουτοι","ετουτον","ετουτος","ετουτου","ετουτους","ετουτων","ετσι","ευγε","ευθυς","ευτυχως","εφεξης"," εχει","εχεις","εχετε","εχθες","εχομε","εχουμε","εχουν","εχτες","εχω","εως","εἰ","εἰμί","εἰμὶ","εἰς","εἰσ","εἴ"," εἴμι","εἴτε","ε∆ω","η","ημασταν","ημαστε","ημουν","ησασταν","ησαστε","ησουν","ηταν","ητανε","ητοι","ηττον"," η∆η","θα","ι","ιι","ιιι","ισαμε","ισια","ισως","ισωσ","ι∆ια","ι∆ιαν","ι∆ιας","ι∆ιες","ι∆ιο","ι∆ιοι","ι∆ιον","ι∆ιος","ι∆ιου","ι∆ιους","ι∆ιων","ι∆ιως","κ","καί","καίτοι","καθ","καθε","καθεμια","καθεμιας"," καθενα","καθενας","καθενος","καθετι","καθολου","καθως","και","κακα","κακως","καλα"," καλως","καμια","καμιαν","καμιας","καμποσα","καμποσες","καμποση","καμποσην","καμποσης","καμποσο","καμποσοι","καμποσον","καμποσος","καμποσου","καμποσους","καμποσων","κανεις","κανεν"," κανενα","κανεναν","ελα","κανενος","καποια","καποιαν","καποιας","καποιες","καποιο"," καποιοι","καποιον","καποιος","καποιου","καποιους","καποιων","καποτε","καπου","καπως","κατ","κατά","κατα","κατι","κατιτι","κατοπιν","κατω","κατὰ","καὶ","κι","κιολας","κλπ","κοντα"," κτλ","κυριως","κἀν","κἂν","λιγακι","λιγο","λιγωτερο","λογω","λοιπα","λοιπον","μέν"," μέσα","μή","μήτε","μία","μα","μαζι","μακρυα","μαλιστα","μαλλον","μας","με","μεθ","εγώ","μειον"," μελει","μελλεται","μεμιας","μεν","μερικα","μερικες","μερικοι","μερικους","μερικων","μεσα","μετ","μετά","μετα"," μεταξυ","μετὰ","μεχρι","μη","μην","μηπως","μητε","μη∆ε","μιά","μια","μιαν","μιας","μολις","μολονοτι","μοναχα"," μονες","μονη","μονην","μονης","μονο","μονοι","μονομιας","μονος","μονου","μονους","μονων","μου"," μπορουν","μπραβο","μπρος","μἐν","μὲν","μὴ","μὴν","να","ναι","νωρις","ξανα","ξαφνικα", "ο","οι","ολα","ολες","ολη","ολην","ολης","ολο","ολογυρα","ολοι","ολον","ολονεν","ολος"," ολοτελα","ολου","ολους","ολων","ολως","ολως∆ιολου","ομως","ομωσ","οποια","οποιαν"," οποιαν∆ηποτε","οποιας","οποιας∆ηποτε","οποια∆ηποτε","οποιες","οποιες∆ηποτε","οποιο" ,"οποιοι","οποιον","οποιον∆ηποτε","οποιος","οποιος∆ηποτε","οποιου","οποιους","οποιους∆ ηποτε","οποιου∆ηποτε","οποιο∆ηποτε","οποιων","οποιων∆ηποτε","οποι∆ηποτε","οποτε","οποτε∆ ηποτε","οπου","οπου∆ηποτε","οπως","οπωσ","ορισμενα","ορισμενες","ορισμενων"," ορισμενως","οσα","οσα∆ηποτε","οσες","οσες∆ηποτε","οση","οσην","οσην∆ηποτε","οσης"," οσης∆ηποτε","οση∆ηποτε","οσο","οσοι","οσοι∆ηποτε","οσον","οσον∆ηποτε","οσος","οσος∆ ηποτε","οσου","οσους","οσους∆ηποτε","οσου∆ηποτε","οσο∆ηποτε","οσων","οσων∆ηποτε","οταν","οτι","οτι∆ηποτε","οτου","ου","ουτε","ου∆ε","οχι","οἱ","οἳ","οἷς","οὐ","οὐδ","οὐδέ","οὐδείσ","οὐδεὶς","οὐδὲ","οὐδὲν","οὐκ","οὐχ","οὐχὶ","οὓς","οὔτε","οὕτω","οὕτως","οὕτωσ","οὖν","οὗ","οὗτος","οὗτοσ","παλι","εγώ"," παντου","παντως","παρ","παρά","παρα","παρὰ","περί","περα","περι","περιπου","περσι","περυσι","περὶ","πια","πιθανον","πιο","πισω","πλαι","πλεον","πλην","ποια","ποιαν","ποιας","ποιες","ποιεσ","ποιο","ποιοι","ποιον","ποιος","ποιοσ","ποιου","ποιους"," ποιουσ","ποιων","πολυ","ποσες","ποση","ποσην","ποσης","ποσοι","ποσος","ποσους","ποτε","που","πουθε","είναι","ποῦ","πρεπει","πριν","προ","προκειμενου","προκειται","απ’","προς","προσ"," προτου","προχθες","προχτες","πρωτυτερα","πρόσ","πρὸ","πρὸς","πως","πωσ","σαν","σας","σε","σεις","αυτό","σιγα","σου","στα","στη","στην","στης","στις","στο","στον","στου","στους","στων","όπως"," συν","συναμα","συνεπως","συνηθως","συχνα","συχνας","συχνες","συχνη","συχνην"," συχνης","συχνο","συχνοι","συχνον","συχνος","συχνου","συχνους","συχνων","συχνως"," σχε∆ον","σωστα","σόσ","σύ","σύν","σὸς","σὺ","σὺν","τά","τήν","τί","τίς","τίσ","τα","ταυτα","ταυτες","ταυτη"," ταυτην","ταυτης","ταυτο,ταυτον","ταυτος","ταυτου","ταυτων","ταχα","ταχατε","ταῖς","τα∆ε","τε","τελικα"," τελικως","τες","τετοια","τετοιαν","τετοιας","τετοιες","τετοιο","τετοιοι","τετοιον","τετοιος","τετοιου","τετοιους", "τετοιων","τη","την","της","τησ","τι","τινα","τιποτα","τιποτε","τις","τισ","το","τοί","τοι","τοιοῦτος","τοιοῦτοσ"," τον","τος","τοσα","τοσες","τοση","τοσην","τοσης","τοσο","τοσοι","τοσον","τοσος","τοσου","τοσους","τοσων","τοτε","του","τουλαχιστο","έλα","τους","τουτα","τουτες","τουτη" ,"τουτην","τουτης","τουτο","τουτοι","τουτοις","τουτον","τουτος","τουτου","τουτους"," τουτων","τούσ","τοὺς","τοῖς","τοῦ","τυχον","των","τωρα","τό","τόν","τότε","τὰ","τὰς","τὴν" ,"τὸ","τὸν","τῆς","τῆσ","τῇ","τῶν","τῷ","υπ","υπερ","υπο","υποψη","υποψιν","υπό","υστερα","φετος","χθες","χτες","χωρις","χωριστα","ω","ωραια","ως","ωσ","ωσαν","ωσοτου","ωσπου","ωστε","ωστοσο","ωχ","ἀλλ'","ἀλλά","ἀλλὰ","ἀλλ’","ἀπ","ἀπό","ἀπὸ", "ἀφ","ἂν","ἃ","ἄλλος","ἄλλοσ","ἄν","ἄρα","ἅμα","ἐάν","ἐγώ","ἐγὼ","ἐκ","ἐμόσ","ἐμὸς","ἐν"," ἐξ","ἐπί","ἐπεὶ","ἐπὶ","ἐστι","ἐφ","ἐὰν","ἑαυτοῦ","ἔτι","ἡ","ἢ","ἣ","ἤ","ἥ","ἧς","ἵνα","ὁ","ὃ","ὃν","ὃς","ὅ","ὅδε"," ὅθεν","ὅπερ","ὅς","ὅσ","ὅστις","ὅστισ","ὅτε","ὅτι","ὑμόσ","ὑπ","ὑπέρ","ὑπό","ὑπὲρ","ὑπὸ", "ὡς","ὡσ","ὥς","ὥστε","ὦ","ᾧ","∆α","∆ε","∆εινα","∆εν","∆εξια","∆ηθεν","∆ηλα∆η","∆ι","∆ ια","∆ιαρκως","∆ικα","∆ικο","∆ικοι","∆ικος","∆ικου","∆ικους","∆ιολου","∆ιχως"];

  let explicitWords = ["4r5e", "5h1t", "5hit", "a55", "anal", "anus", "ar5e", "arrse", "arse", "ass", "ass-fucker", "asses", "assfucker", 
  "assfukka", "asshole", "assholes", "asswhole", "a_s_s", "b!tch", "b00bs", "b17ch", "b1tch", "ballbag", "balls", "ballsack", 
  "bastard", "beastial", "beastiality", "bellend", "bestial", "bestiality", "bi+ch", "biatch", "bitch", "bitcher", "bitchers", 
  "bitches", "bitchin", "bitching", "bloody", "blow job", "blowjob", "blowjobs", "boiolas", "bollock", "bollok", "boner", "boob", 
  "boobs", "booobs", "boooobs", "booooobs", "booooooobs", "breasts", "buceta", "bugger", "bum", "bunny fucker", "butt", "butthole", 
  "buttmuch", "buttplug", "c0ck", "c0cksucker", "carpet muncher", "cawk", "chink", "cipa", "cl1t", "clit", "clitoris", "clits", 
  "cnut", "cock", "cock-sucker", "cockface", "cockhead", "cockmunch", "cockmuncher", "cocks", "cocksuck", "cocksucked", 
  "cocksucker", "cocksucking", "cocksucks", "cocksuka", "cocksukka", "cok", "cokmuncher", "coksucka", "coon", "cox", "crap", 
  "cum", "cummer", "cumming", "cums", "cumshot", "cunilingus", "cunillingus", "cunnilingus", "cunt", "cuntlick", "cuntlicker", 
  "cuntlicking", "cunts", "cyalis", "cyberfuc", "cyberfuck", "cyberfucked", "cyberfucker", "cyberfuckers", "cyberfucking", 
  "d1ck", "damn", "dick", "dickhead", "dildo", "dildos", "dink", "dinks", "dirsa", "dlck", "dog-fucker", "doggin", "dogging", 
  "donkeyribber", "doosh", "duche", "dyke", "ejaculate", "ejaculated", "ejaculates", "ejaculating", "ejaculatings", "ejaculation", 
  "ejakulate", "f u c k", "f u c k e r", "f4nny", "fag", "fagging", "faggitt", "faggot", "faggs", "fagot", "fagots", "fags", 
  "fanny", "fannyflaps", "fannyfucker", "fanyy", "fatass", "fcuk", "fcuker", "fcuking", "feck", "fecker", "felching", "fellate", 
  "fellatio", "fingerfuck", "fingerfucked", "fingerfucker", "fingerfuckers", "fingerfucking", "fingerfucks", "fistfuck", 
  "fistfucked", "fistfucker", "fistfuckers", "fistfucking", "fistfuckings", "fistfucks", "flange", "fook", "fooker", "fuck", 
  "fucka", "fucked", "fucker", "fuckers", "fuckhead", "fuckheads", "fuckin", "fucking", "fuckings", "fuckingshitmotherfucker", 
  "fuckme", "fucks", "fuckwhit", "fuckwit", "fudge packer", "fudgepacker", "fuk", "fuker", "fukker", "fukkin", "fuks", "fukwhit", 
  "fukwit", "fux", "fux0r", "f_u_c_k", "gangbang", "gangbanged", "gangbangs", "gaylord", "gaysex", "goatse", "god-dam", 
  "god-damned", "goddamn", "goddamned", "hardcoresex", "hell", "heshe", "hoar", "hoare", "hoer", "homo", "hore", "horniest", 
  "horny", "hotsex", "jack-off", "jackoff", "jap", "jerk-off", "jism", "jiz", "jizm", "jizz", "kawk", "knob", "knobead", 
  "knobed", "knobend", "knobhead", "knobjocky", "knobjokey", "kock", "kondum", "kondums", "kum", "kummer", "kumming", "kums", 
  "kunilingus", "l3i+ch", "l3itch", "labia", "lust", "lusting", "m0f0", "m0fo", "m45terbate", "ma5terb8", "ma5terbate", 
  "masochist", "master-bate", "masterb8", "masterbat*", "masterbat3", "masterbate", "masterbation", "masterbations", 
  "masturbate", "mo-fo", "mof0", "mofo", "mothafuck", "mothafucka", "mothafuckas", "mothafuckaz", "mothafucked", "mothafucker", 
  "mothafuckers", "mothafuckin", "mothafucking", "mothafuckings", "mothafucks", "mother fucker", "motherfuck", "motherfucked", 
  "motherfucker", "motherfuckers", "motherfuckin", "motherfucking", "motherfuckings", "motherfuckka", "motherfucks", "muff", 
  "mutha", "muthafecker", "muthafuckker", "muther", "mutherfucker", "n1gga", "n1gger", "nazi", "nigg3r", "nigg4h", "nigga", 
  "niggah", "niggas", "niggaz", "nigger", "niggers", "nob", "nob jokey", "nobhead", "nobjocky", "nobjokey", "numbnuts", "nutsack", 
  "orgasim", "orgasims", "orgasm", "orgasms", "p0rn", "pawn", "pecker", "penis", "penisfucker", "phonesex", "phuck", "phuk", 
  "phuked", "phuking", "phukked", "phukking", "phuks", "phuq", "pigfucker", "pimpis", "piss", "pissed", "pisser", "pissers", 
  "pisses", "pissflaps", "pissin", "pissing", "pissoff", "poop", "porn", "porno", "pornography", "pornos", "prick", "pricks", 
  "pron", "pube", "pusse", "pussi", "pussies", "pussy", "pussys", "rectum", "retard", "rimjaw", "rimming", "s hit", "s.o.b.", 
  "sadist", "schlong", "screwing", "scroat", "scrote", "scrotum", "semen", "sex", "sh!+", "sh!t", "sh1t", "shag", "shagger", 
  "shaggin", "shagging", "shemale", "shi+", "shit", "shitdick", "shite", "shited", "shitey", "shitfuck", "shitfull", "shithead", 
  "shiting", "shitings", "shits", "shitted", "shitter", "shitters", "shitting", "shittings", "shitty", "skank", "slut", "sluts", 
  "smegma", "smut", "snatch", "son-of-a-bitch", "spac", "spunk", "s_h_i_t", "t1tt1e5", "t1tties", "teets", "teez", "testical", 
  "testicle", "tit", "titfuck", "tits", "titt", "tittie5", "tittiefucker", "titties", "tittyfuck", "tittywank", "titwank", "tosser", 
  "turd", "tw4t", "twat", "twathead", "twatty", "twunt", "twunter", "v14gra", "v1gra", "vagina", "viagra", "vulva", "w00se", "wang", 
  "wank", "wanker", "wanky", "whoar", "whore", "willies", "willy", "xrated", "xxx", "fuckin'"];